name: Bench

on:
  push:
    branches:
      - main
      - bench
    tags:
      - 'v*.*.*'

jobs:
  bench:
    name: Bench
    runs-on: ubuntu-latest
    if: github.repository == 'c4spar/deno-cliffy'
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Pre benchmarks
        env:
          CLIFFY_BOT_PAT: ${{ secrets.CLIFFY_BOT_PAT }}
        run: |
          git clone --depth 1 --branch main \
              https://${CLIFFY_BOT_PAT}@github.com/c4spar/cliffy-benchmarks.git \
              benchmark_data

      - name: Run benchmarks (tags)
        run: |
          if ! test -f benchmark_data/bench.json; then
            git fetch --tags
            cp -r bench bench_tmp
            for tag in $(git tag); do
              git checkout $tag
              deno run \
                --no-check \
                --allow-read=benchmark_data/bench.json \
                --allow-write=benchmark_data/bench.json \
                bench_tmp/main.ts \
                benchmark_data/bench.json ${tag} || echo "Benchmark for ${tag} failed!"
            done
            rm -rf bench_tmp
            git checkout $GITHUB_SHA
          else
            echo bench.json already exists!
          fi

      - name: Run benchmarks (tag)
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          release_version=${GITHUB_REF#refs/*/}
          deno run \
            --allow-read=benchmark_data/bench.json \
            --allow-write=benchmark_data/bench.json \
            bench/main.ts \
            benchmark_data/bench.json ${release_version}

      - name: Run benchmarks (rev)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          rev=$(git rev-parse --short "$GITHUB_SHA")
          deno run \
            --allow-read=benchmark_data/dev_bench.json \
            --allow-write=benchmark_data/dev_bench.json \
            bench/main.ts \
            benchmark_data/dev_bench.json ${rev}

      - name: Post benchmarks
        run: |
          cd benchmark_data
          git checkout -b test
          git config user.email "c4spar@gmx.de"
          git config user.name "cliffy-bot"
          git add .
          git commit --message "chore(bench): update benchmarks"
          git push origin test

