name: ci

on: [push, pull_request]

jobs:

  build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        deno_version: [ 'v1.0.0' ]

    steps:
    - name: Configure git
      run: git config --global core.symlinks true

    - name: Clone repository
      uses: actions/checkout@v2

    - name: Configure environment variable's
      run: |
        echo "::set-env name=DENO_INSTALL::$HOME/.local"
        echo "::add-path::$HOME/.local/bin"

    - name: Install deno ${{ matrix.deno_version }}
      run: |
        curl -fsSL https://deno.land/x/install/install.sh | sh -s ${{ matrix.deno_version }}
        deno -h

    - name: Run command test's
      run: deno test packages/command

    - name: Run flags test's
      run: deno test packages/flags

    - name: Run keycode test's
      run: deno test packages/keycode

    - name: Run prompt test's
      run: deno test packages/prompt --unstable

    - name: Run table test's
      run: deno test packages/table
